spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: bus-service
          uri: http://localhost:8087
          predicates:
            - Path=/api/bus,/api/bus/**,/api/bookings,/api/bookings/**

        - id: feedback-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/feedback,/api/feedback/**

        - id: user-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/login,/api/register,/api/user/**
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
